name: overlord

volumes:
  postgres:
  minio:

networks:
  common:

services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-overlord}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_USER=${POSTGRES_USER:-user}
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - common

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY:-minioadmin123}
      - MINIO_DOMAIN=${MINIO_DOMAIN:-localhost}
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio:/data
    networks:
      - common

  minio-init:
    image: minio/mc
    restart: no
    entrypoint: >
      sh -c
      "sleep 2
      && mc alias set myminio http://minio:9000 minioadmin minioadmin123
      && mc mb myminio/images || true
      && mc mb myminio/util || true
      && mc anonymous set download myminio/images"
    depends_on:
      minio:
        condition: service_started
    networks:
      - common

  accounter:
    image: ghcr.io/tbank-presentation-pp5/accounter:main
    container_name: accounter
    ports:
      - '8001:8001'
    environment:
      - HOST=${HOST_IP_ACCOUNTER:-0.0.0.0}
      - PORT=${PORT_ACCOUNTER:-8001}
      - LOG_LEVEL=${LOG_LEVEL_ACCOUNTER:-INFO}
      - TZ=UTC
      - PYTHONUNBUFFERED=1
      - DB_PATH=/data/auth.db
    volumes:
      - ./data:/data
    restart: unless-stopped
    networks:
      - common

  collabora: # https://github.com/CollaboraOnline/online
    image: collabora/code:25.04.8.2.1
    restart: unless-stopped
    environment:
      - username=admin # admin ui /browser/dist/admin/admin.html
      - password=admin
      - extra_params=--o:ssl.enable=false --o:logging.level=warning --o:logging.level_startup=warning
    ports:
      - '9980:9980'
    networks:
      - common

  app:
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-overlord}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}

      - CF_ID_ACCOUNT=${CF_ID_ACCOUNT}
      - CF_AUTH_TOKEN=${CF_AUTH_TOKEN}

      - ACCOUNTER_URL=${ACCOUNTER_URL:-http://accounter:8001}
      - ACCOUNTER_ENABLED=${ACCOUNTER_ENABLED:-true}

      - MINIO_USER=${MINIO_USER:-minioadmin}
      - MINIO_PASSWORD=${MINIO_PASSWORD:-minioadmin123}
      - MINIO_BUCKET=${MINIO_BUCKET:-images}
      - MINIO_BUCKET_UTIL=${MINIO_BUCKET_UTIL:-util}
      - MINIO_CONNECTION_URL=${MINIO_CONNECTION_URL:-http://minio:9000}
      - MINIO_PUBLIC_DOMAIN=${MINIO_PUBLIC_DOMAIN:-localhost:9000}

      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
    ports:
      - '8080:8080'
    depends_on:
      minio:
        condition: service_started
      minio-init:
        condition: service_completed_successfully
      postgres:
        condition: service_started
      accounter:
        condition: service_started
    networks:
      - common
