name: overlord

volumes:
  postgres:
  minio:
  kafka:

networks:
  common:

services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-overlord}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_USER=${POSTGRES_USER:-user}
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - common

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY:-minioadmin123}
      - MINIO_DOMAIN=${MINIO_DOMAIN:-localhost}
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio:/data
    networks:
      - common

  minio-init:
    image: minio/mc
    restart: no
    entrypoint: >
      sh -c
      "sleep 2
      && mc alias set myminio http://minio:9000 minioadmin minioadmin123
      && mc mb myminio/images || true
      && mc mb myminio/util || true
      && mc anonymous set download myminio/images"
    depends_on:
      minio:
        condition: service_started
    networks:
      - common

  accounter:
    image: ghcr.io/tbank-presentation-pp5/accounter:main
    container_name: accounter
    ports:
      - '8001:8001'
    environment:
      - HOST=${HOST_IP_ACCOUNTER:-0.0.0.0}
      - PORT=${PORT_ACCOUNTER:-8001}
      - LOG_LEVEL=${LOG_LEVEL_ACCOUNTER:-INFO}
      - TZ=UTC
      - PYTHONUNBUFFERED=1
      - DB_PATH=/data/auth.db
    volumes:
      - ./data:/data
    restart: unless-stopped
    networks:
      - common

  collabora: # https://github.com/CollaboraOnline/online
    image: collabora/code:25.04.8.2.1
    restart: unless-stopped
    environment:
      - username=admin # admin ui /browser/dist/admin/admin.html
      - password=admin
      - extra_params=--o:ssl.enable=false --o:logging.level=warning --o:logging.level_startup=warning
    ports:
      - '9980:9980'
    networks:
      - common

  kafka:
    image: apache/kafka-native:4.1.1
    restart: unless-stopped
    hostname: kafka
    user: root
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT_HOST://localhost:9092,PLAINTEXT://kafka:19092
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:29093
      - KAFKA_LISTENERS=CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - CLUSTER_ID=4L6g3nShT-eMCtK--X86sw
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR=1
      - KAFKA_LOG_DIRS=/var/lib/kafka/data
    ports:
      - '9092:9092'
    volumes:
      - kafka:/var/lib/kafka/data
    networks:
      - common

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    restart: unless-stopped
    container_name: kafka-ui
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:19092
      - KAFKA_CLUSTERS_0_CONTROLLER_BOOTSTRAP_SERVERS=kafka:29093
      - AUTH_TYPE=LOGIN_FORM
      - SPRING_SECURITY_USER_NAME=admin
      - SPRING_SECURITY_USER_PASSWORD=admin
    ports:
      - '8081:8080'
    depends_on:
      kafka:
        condition: service_started
    networks:
      - common

  app:
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-overlord}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}

      - CF_ID_ACCOUNT=${CF_ID_ACCOUNT}
      - CF_AUTH_TOKEN=${CF_AUTH_TOKEN}

      - ACCOUNTER_URL=${ACCOUNTER_URL:-http://accounter:8001}
      - ACCOUNTER_ENABLED=${ACCOUNTER_ENABLED:-true}

      - MINIO_USER=${MINIO_USER:-minioadmin}
      - MINIO_PASSWORD=${MINIO_PASSWORD:-minioadmin123}
      - MINIO_BUCKET=${MINIO_BUCKET:-images}
      - MINIO_BUCKET_UTIL=${MINIO_BUCKET_UTIL:-util}
      - MINIO_CONNECTION_URL=${MINIO_CONNECTION_URL:-http://minio:9000}
      - MINIO_PUBLIC_DOMAIN=${MINIO_PUBLIC_DOMAIN:-localhost:9000}

      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
    ports:
      - '8080:8080'
    depends_on:
      minio:
        condition: service_started
      minio-init:
        condition: service_completed_successfully
      postgres:
        condition: service_started
      accounter:
        condition: service_started
    networks:
      - common
