spring:
  application:
    name: overlord
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:overlord}
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  show-actuator: true

cloudflare:
  id-account: ${CF_ID_ACCOUNT}
  auth-token: ${CF_AUTH_TOKEN}
  api-text-style: ${CF_API_TEXT_STYLE:responses}  # или path
  path-style-model: ${CF_PATH_STYLE_MODEL:@cf/mistralai/mistral-small-3.1-24b-instruct}
  responses-style-model: ${CF_RESPONSES_STYLE_MODEL:@cf/openai/gpt-oss-120b}
  image-base64-model: ${CF_IMAGE_BASE64_MODEL:@cf/black-forest-labs/flux-1-schnell}

accounter:
  url: ${ACCOUNTER_URL:http://localhost:8001}
  enabled: ${ACCOUNTER_ENABLED:false}

minio:
  user: ${MINIO_USER:minioadmin}
  password: ${MINIO_PASSWORD:minioadmin123}
  bucket: ${MINIO_BUCKET:images}
  util-bucket: ${MINIO_BUCKET_UTIL:util}
  connect-url: ${MINIO_CONNECTION_URL:http://localhost:9000}
  public-url: ${MINIO_PUBLIC_URL:http://localhost:9000}
